#!/bin/bash

if [ "$#" == "0" ]; then
	echo "Usage: ./as2shell file"
	exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TMPDIR=`mktemp -d`
trap "rm -rf $TMPDIR" EXIT

# Convert asm to bin
as $1 -o $TMPDIR/$1b2s.o

if [ $? -eq 0 ]; then
	objcopy -O binary $TMPDIR/$1b2s.o $TMPDIR/$1b2s.bin

	if [ -x $DIR/bin2shell ]; then
		if [ $? -eq 0 ]; then
			# convert bin to shell
			$DIR/bin2shell $TMPDIR/$1b2s.bin
		fi
	else
		echo "Error: couldn't find bin2shell executable"
	fi
else
	echo "Error: couldn't generate binary"
fi
